services:
  mfcbot:
    image: mfcbot
    user: 1001:1001
    entrypoint: ["/usr/bin/env", "sh", "/app/run.sh"]
    volumes:
      - ./mfcbot.db:/app/mfcbot.db
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - mfcgo

  mfcgo:
    image: mfcgo
    restart: unless-stopped
